// Server-side signup validation - blocks disposable emails and checks fingerprint abuse
import { createClient } from '@supabase/supabase-js';

// Comprehensive list of disposable email domains (200+)
const DISPOSABLE_EMAIL_DOMAINS = [
  // Popular disposable email services
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  'tempmail.com', 'temp-mail.org', 'temp-mail.io',
  'guerrillamail.com', 'guerrillamail.org', 'guerrillamail.net', 'guerrillamail.biz',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'throwaway.email', 'throwawaymail.com',
  'fakeinbox.com', 'fakeinbox.net',
  'trashmail.com', 'trashmail.net', 'trashmail.org',
  'getnada.com', 'nada.email',
  'dispostable.com',
  'mailnesia.com',
  'tempinbox.com',
  'burnermail.io',
  'mohmal.com',
  'sharklasers.com', 'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'grr.la',
  'spamgourmet.com',
  'mytrashmail.com',
  'mt2009.com', 'mt2014.com', 'mt2015.com',
  'thankyou2010.com',
  'trash2009.com',
  'dodgeit.com',
  'mailexpire.com',
  'spamex.com',
  'emailondeck.com',
  'tempr.email',
  'discard.email',
  'discardmail.com',
  'mailcatch.com',
  'inboxalias.com',
  'jetable.org',
  'maildrop.cc',
  'getairmail.com',
  'mintemail.com',
  'spamavert.com',
  'spamfree24.org',
  'spamherelots.com',
  'spamobox.com',
  'tempomail.fr',
  'tmpmail.org', 'tmpmail.net',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'emailfake.com',
  'emkei.cz',
  'crazymailing.com',
  'mailnull.com',
  'mailscrap.com',
  'mailslite.com',
  'sofimail.com',
  'veryrealemail.com',
  'mailforspam.com',
  'spamspot.com',
  'spam.la',
  'binkmail.com',
  'safetymail.info',
  'spamfree.eu',
  'guerrillamail.de',
  'hulapla.de',
  'mail-temporaire.fr',
  'mail.by',
  'mailmetrash.com',
  'meltmail.com',
  'objectmail.com',
  'proxymail.eu',
  'rcpt.at',
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trashymail.com', 'trashymail.net',
  'trbvm.com',
  'twinmail.de',
  'uggsrock.com',
  'upliftnow.com',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viralplays.com',
  'vkcode.ru',
  'whatpaas.com',
  'wh4f.org',
  'xagloo.co',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yuurok.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',
  'anonmails.de',
  'anonymbox.com',
  'antispam.de',
  'baxomale.ht.cx',
  'beefmilk.com',
  'binkmail.com',
  'bobmail.info',
  'bofthew.com',
  'bootybay.de',
  'boun.cr',
  'bouncr.com',
  'breakthru.com',
  'brefmail.com',
  'brennendesreich.de',
  'broadbandnits.com',
  'bsnow.net',
  'buffemail.com',
  'bugmenot.com',
  'bumpymail.com',
  'bund.us',
  'bundes-ede',
  'burnthespam.info',
  'buyusedlibrarybooks.org',
  'byom.de',
  'c2.hu',
  'cachedot.net',
  'casualdx.com',
  'cellurl.com',
  'centermail.com', 'centermail.net',
  'cheatmail.de',
  'chogmail.com',
  'choicemail1.com',
  'clixser.com',
  'cmail.com', 'cmail.net', 'cmail.org',
  'coldemail.info',
  'consumerriot.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'curryworld.de',
  'cust.in',
  'cuvox.de',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'dcemail.com',
  'deadaddress.com',
  'deadspam.com',
  'delikkt.de',
  'despam.it',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'dingbone.com',
  'disposableaddress.com',
  'disposableemailaddresses.com',
  'disposableinbox.com',
  'dispose.it',
  'disposemail.com',
  'dispomail.eu',
  'dm.w3internet.co.uk',
  'dodgeit.com',
  'dodgit.com', 'dodgit.org',
  'donemail.ru',
  'dontreg.com', 'dontsendmespam.de',
  'drdrb.com',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e-mail.com', 'e-mail.org',
  'e4ward.com',
  'easytrashmail.com',
  'einmalmail.de',
  'email60.com',
  'emaildienst.de',
  'emailgo.de',
  'emailias.com',
  'emailigo.de',
  'emailinfive.com',
  'emaillime.com',
  'emailmiser.com',
  'emailsensei.com',
  'emailtemporanea.com', 'emailtemporanea.net',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emailthe.net',
  'emailtmp.com',
  'emailto.de',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emeil.in', 'emeil.ir',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'ero-tube.org',
  'etranquil.com', 'etranquil.net', 'etranquil.org',
  'evopo.com',
  'explodemail.com',
  'express.net.ua',
  'eyepaste.com',
  'facebook-email.cf', 'facebook-email.ga', 'facebook-email.ml',
  'fakedemail.com',
  'fakeinbox.cf', 'fakeinbox.ga', 'fakeinbox.ml', 'fakeinbox.tk',
  'fakemailgenerator.com',
  'fammix.com',
  'fangoh.com',
  'fastacura.com', 'fastchevy.com', 'fastchrysler.com',
  'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com',
  'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com',
  'fettomeansen.com',
  'fightallspam.com',
  'filzmail.com',
  'fixmail.tk',
  'fizmail.com',
  'flyspam.com',
  'fr33mail.info',
  'frapmail.com',
  'friendlymail.co.uk',
  'front14.org',
  'fuckingduh.com',
  'fudgerub.com',
  'fux0ringduh.com',
  'garliclife.com',
  'gehensiull.com',
  'get2mail.fr',
  'getonemail.com', 'getonemail.net',
  'ghosttexter.de',
  'giantmail.de',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'goemailgo.com',
  'gorillaswithdirtyarmpits.com',
  'gotmail.com', 'gotmail.net', 'gotmail.org',
  'gotti.otherinbox.com',
  'gowikibooks.com', 'gowikicampus.com', 'gowikicars.com',
  'gowikifilms.com', 'gowikigames.com', 'gowikimusic.com',
  'gowikinetwork.com', 'gowikitravel.com', 'gowikitv.com',
  'grandmamail.com', 'grandmasmail.com',
  'great-host.in',
  'greensloth.com',
  'gsrv.co.uk',
  'guerillamail.biz', 'guerillamail.com', 'guerillamail.de',
  'guerillamail.net', 'guerillamail.org',
  'guerrillamail.info',
  'h.mintemail.com',
  'h8s.org',
  'hacccc.com',
  'haltospam.com',
  'hatespam.org',
  'herp.in',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'hochsitze.com',
  'hopemail.biz',
  'hotpop.com',
  'hulapla.de',
  'ieatspam.eu', 'ieatspam.info',
  'ihateyoualot.info',
  'iheartspam.org',
  'imails.info',
  'imgof.com',
  'imgv.de',
  'imstations.com',
  'inbax.tk',
  'inbox.si',
  'inboxclean.com', 'inboxclean.org',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'infocom.zp.ua',
  'insorg-mail.info',
  'instant-mail.de',
  'instantemailaddress.com',
  'iozak.com',
  'ipoo.org',
  'irish2me.com',
  'iwi.net',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'jnxjn.com',
  'jourrapide.com',
  'jsrsolutions.com',
  'junk1.com',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com', 'killmail.net',
  'kimsdisk.com',
  'kingsq.ga',
  'kiois.com',
  'kir.ch.tc',
  'klassmaster.com', 'klassmaster.net',
  'klzlv.com',
  'kook.ml',
  'kulturbetrieb.info',
  'kurzepost.de',
  'lawlita.com',
  'lazyinbox.com',
  'legitmail.club',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'loadby.us',
  'login-email.cf', 'login-email.ga', 'login-email.ml', 'login-email.tk',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lovemeleaveme.com',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'm4ilweb.info',
  'maboard.com',
  'mail-hierarchie.net',
  'mail.by', 'mail.mezimages.net', 'mail.zp.ua',
  'mail114.net',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailblocks.com',
  'mailcatch.com',
  'mailde.de', 'mailde.info',
  'maildrop.cc', 'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml',
  'maildu.de',
  'maildx.com',
  'mailed.ro',
  'mailexpire.com',
  'mailfa.tk',
  'mailfork.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.co.uk', 'mailinator.info', 'mailinator.us', 
  'mailinator2.com', 'mailinator2.net',
  'mailincubator.com',
  'mailismagic.com',
  'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq', 'mailjunk.ml', 'mailjunk.tk',
  'mailmate.com',
  'mailme.gq', 'mailme.ir', 'mailme.lv',
  'mailme24.com',
  'mailmetrash.com', 'mailmetrash.comilzilla.org',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailpick.biz',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailzilla.com', 'mailzilla.org', 'mailzilla.orgmbx.cu.cc',
  'makemetheking.com',
  'manifestgenerator.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mierdamail.com',
  'migmail.pl',
  'migumail.com',
  'mintemail.com',
  'mjukgansen.nu',
  'moakt.com',
  'mobi.web.id',
  'mobileninja.co.uk',
  'moburl.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'ms9.mailslite.com',
  'msa.minsmail.com',
  'msb.minsmail.com',
  'msg.mailslite.com',
  'mspec.com',
  'mt2009.com', 'mt2014.com', 'mt2015.com',
  'mtmdev.com',
  'mucinoustrede.com',
  'mufmail.com',
  'mvrht.com',
  'mxfuel.com',
  'my10minutemail.com',
  'mycleaninbox.net',
  'myemailboxy.com',
  'mymail-in.net',
  'mymailoasis.com',
  'mynetstore.de',
  'mypacks.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'mysamp.de',
  'myspaceinc.com', 'myspaceinc.net',
  'myspacepimpedup.com',
  'myspamless.com',
  'mytempemail.com',
  'mytempmail.com',
  'mytrashmail.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtmansen.com',
  'netmails.com', 'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.hu',
  'nmail.cf',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net', 'nospamthanks.info',
  'notmailinator.com',
  'nowhere.org',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'nwytg.com', 'nwytg.net',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'one-time.email',
  'oneoffemail.com',
  'onewayemail.com', 'onewaymail.com',
  'online.ms',
  'oopi.org',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'privy-mail.com', 'privymail.de',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'pwrby.com',
  'qisdo.com', 'qisoa.com',
  'quickinbox.com',
  'quickmail.nl',
  'rainmail.biz',
  'rcpt.at',
  're-gister.com',
  'reallymyemail.com',
  'realtyalerts.ca',
  'recode.me',
  'recursor.net',
  'recyclemail.dk',
  'regbypass.com', 'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'remail.cf', 'remail.ga',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info', 'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz', 'secure-mail.cc',
  'selfdestructingmail.com',
  'senseless-entertainment.com',
  'server.ms.selfip.net',
  'sharklasers.com',
  'shieldemail.com',
  'shiftmail.com',
  'shitmail.me', 'shitmail.org',
  'shortmail.net',
  'shut.name', 'shut.ws',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'skeefmail.com',
  'slaskpost.se',
  'slave-auctions.net',
  'slopsbox.com',
  'slushmail.com',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la', 'spam.su', 'spam4.me',
  'spamail.de',
  'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.net', 'spambog.ru',
  'spambox.info', 'spambox.irishspringrealty.com', 'spambox.us',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com',
  'spameater.com', 'spameater.org',
  'spamex.com',
  'spamfree.eu', 'spamfree24.com', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgoes.in',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com', 'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'squizzy.de',
  'ssoia.com',
  'startkeys.com',
  'stexsy.com',
  'stinkefinger.net',
  'stop-my-spam.cf', 'stop-my-spam.ga', 'stop-my-spam.ml', 'stop-my-spam.tk',
  'streetwisemail.com',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com', 'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tagyourself.com',
  'talkinator.com',
  'tapchicuoihoi.com',
  'techemail.com',
  'techgroup.me',
  'teewars.org',
  'teleosaurs.xyz',
  'teleworm.com', 'teleworm.us',
  'temp.emeraldwebmail.com',
  'temp.headstrong.de',
  'tempail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz', 'tempemail.co.za', 'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempinbox.com',
  'tempmail.co', 'tempmail.de', 'tempmail.eu', 'tempmail.it', 'tempmail.net',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com', 'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tempthe.net',
  'thankyou2010.com',
  'thecloudindex.com',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'throam.com',
  'throwawayemailaddress.com',
  'throwawaymail.com',
  'tilien.com',
  'tittbit.in',
  'tmailinator.com',
  'toiea.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de', 'trash-mail.ga', 'trash-mail.gq', 'trash-mail.ml', 'trash-mail.tk',
  'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashbox.eu',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de',
  'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmail.ws',
  'trashmailer.com',
  'trashymail.com', 'trashymail.net',
  'trbvm.com', 'trbvn.com',
  'trickmail.net',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'twoweirdtricks.com',
  'tyldd.com',
  'ubismail.net',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'valemail.net',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'viralplays.com',
  'vkcode.ru',
  'vmailing.info',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'webuser.in',
  'wee.my',
  'weg-werf-email.de',
  'wegwerf-email-addressen.de', 'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org',
  'wetrainbayarea.com', 'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com', 'whatpaas.com',
  'whopy.com',
  'whtjddn.33mail.com',
  'whyspam.me',
  'wilemail.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wolfsmail.tk',
  'wollan.info',
  'worldspace.link',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.co', 'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.gq', 'yopmail.net',
  'yordanmail.cf',
  'yourdomain.com',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminuten.de', 'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.com', 'zoemail.net', 'zoemail.org',
  'zomg.info',
  'zxcv.com', 'zxcvbnm.com',
  'zzz.com'
];

// Check if email domain is disposable
function isDisposableEmail(email) {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1].toLowerCase();
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

export default async function handler(req, res) {
  // CORS
  const allowedOrigins = ['https://upblock.ai', 'http://localhost:5173', 'http://localhost:3000'];
  const origin = req.headers.origin;
  if (allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Credentials', 'true');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { email, fingerprint } = req.body;

  if (!email) {
    return res.status(400).json({ error: 'Email is required' });
  }

  // Check 1: Disposable email domain
  if (isDisposableEmail(email)) {
    console.log('[ValidateSignup] Blocked disposable email:', email.split('@')[1]);
    return res.status(400).json({ 
      error: 'Please use a permanent email address. Temporary email services are not allowed.',
      code: 'DISPOSABLE_EMAIL'
    });
  }

  // Check 2: Fingerprint abuse (if fingerprint provided)
  if (fingerprint) {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (supabaseUrl && supabaseServiceKey) {
      const supabase = createClient(supabaseUrl, supabaseServiceKey, {
        auth: { persistSession: false }
      });

      try {
        // Check how many accounts this fingerprint has created
        const { data: existingAccounts, error } = await supabase
          .from('profiles')
          .select('id, email, created_at')
          .eq('signup_fingerprint', fingerprint);

        if (!error && existingAccounts && existingAccounts.length >= 2) {
          console.log('[ValidateSignup] Fingerprint abuse detected:', fingerprint.substring(0, 10) + '...', 'accounts:', existingAccounts.length);
          return res.status(400).json({
            error: 'Multiple accounts detected from this device. Please use your existing account.',
            code: 'FINGERPRINT_ABUSE',
            existingEmail: existingAccounts[0].email.replace(/(.{2})(.*)(@.*)/, '$1***$3') // Masked
          });
        }
      } catch (err) {
        // Don't block signup if fingerprint check fails, just log it
        console.error('[ValidateSignup] Fingerprint check error:', err.message);
      }
    }
  }

  // All checks passed
  return res.status(200).json({ valid: true });
}

